using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using Umbraco.Community.PropertyVisibility.Configuration.ConfigFile;
using Umbraco.Community.PropertyVisibility.Tests.TestSupport;

namespace Umbraco.Community.PropertyVisibility.Tests.Configuration;

/// <summary>
///     The committed JSON schemas in the package project (generated by tools/Umbraco.Community.PropertyVisibility.SchemaGenerator;
///     CI fails when they drift from the options model) accept the configuration samples and reject a misspelled key, which
///     is what makes an editor flag it.
/// </summary>
[TestFixture]
public sealed class JsonSchemaTests
{
	private const string AppSettingsSchemaFile = "appsettings-schema.Umbraco.Community.PropertyVisibility.json";
	private const string ConfigFileSchemaFile = "PropertyVisibility.config-schema.json";

	/// <summary>The rules file sample (PropertyVisibility.config.json next to appsettings.json).</summary>
	private const string ConfigFileSample = """
		{
			"$schema": "./PropertyVisibility.config-schema.json",
			// Comments and trailing commas are allowed in the rules file.
			"HideEmptiedContainers": true,
			"ContentTypes": {
				"siteSettings": { "Containers": ["legacyTab"] }
			},
			"Sites": {
				"corporate": {
					"RootNodeKey": "5c2b4d7e-9f1a-4c3e-8b6d-2a1f0e9d8c7b",
					"ContentTypes": {
						"landingPage": { "Containers": ["seoTab"], "Properties": ["relatedLinks"], },
					},
				},
				"everythingElse": { "IsDefault": true },
			},
		}
		""";

	private static readonly JsonDocumentOptions JsonWithComments = new()
	{
		CommentHandling = JsonCommentHandling.Skip,
		AllowTrailingCommas = true,
	};

	private static readonly string RepositoryRoot = FindRepositoryRoot();

	private static string PackageProjectFile(string name) =>
		Path.Combine(RepositoryRoot, "src", "Umbraco.Community.PropertyVisibility", name);

	private static string TestSiteAppSettings =>
		File.ReadAllText(Path.Combine(RepositoryRoot, "src", "Umbraco.Community.PropertyVisibility.TestSite", "appsettings.json"));

	/// <summary>
	///     The test site ships the rules file as a sample under another name, so appsettings stays the active source until
	///     someone copies it to PropertyVisibility.config.json.
	/// </summary>
	private const string TestSiteRulesFileSampleName = "PropertyVisibility.config.sample.json";

	private static string TestSiteRulesFileSample =>
		File.ReadAllText(Path.Combine(RepositoryRoot, "src", "Umbraco.Community.PropertyVisibility.TestSite", TestSiteRulesFileSampleName));

	[Test]
	public void AppSettingsSchema_describes_the_PropertyVisibility_section_the_way_Umbraco_merges_it()
	{
		var schema = JsonNode.Parse(File.ReadAllText(PackageProjectFile(AppSettingsSchemaFile)))!.AsObject();

		// The site's appsettings-schema.json combines this file with Umbraco's and others through allOf, so its root must
		// stay open and declare only the section.
		Assert.That(schema["type"]!.GetValue<string>(), Is.EqualTo("object"));
		Assert.That(schema.ContainsKey("additionalProperties"), Is.False);
		Assert.That(schema["properties"]!.AsObject().Select(p => p.Key), Is.EqualTo(new[] { "PropertyVisibility" }));
	}

	[Test]
	public void AppSettingsSchema_accepts_the_test_site_appsettings()
	{
		var result = Evaluate(AppSettingsSchemaFile, TestSiteAppSettings);

		Assert.That(result.IsValid, Is.True, Describe(result));
	}

	[Test]
	public void AppSettingsSchema_rejects_a_misspelled_key_inside_a_rule_set_rule()
	{
		var appSettings = ReplaceFirst(TestSiteAppSettings, "\"Properties\"", "\"Propertes\"");

		var result = Evaluate(AppSettingsSchemaFile, appSettings);

		Assert.That(result.IsValid, Is.False);
		Assert.That(InvalidLocations(result), Has.Some.EqualTo("/PropertyVisibility/RuleSets/noBannerImage/ContentTypes/landingPage/Propertes"));
	}

	[Test]
	public void AppSettingsSchema_rejects_a_misspelled_key_inside_a_site_rule()
	{
		var sites = TestSiteAppSettings.IndexOf("\"Sites\"", StringComparison.Ordinal);
		Assert.That(sites, Is.GreaterThanOrEqualTo(0), "'\"Sites\"' not found in the sample");
		var appSettings = TestSiteAppSettings[..sites] + ReplaceFirst(TestSiteAppSettings[sites..], "\"Properties\"", "\"Propertes\"");

		var result = Evaluate(AppSettingsSchemaFile, appSettings);

		Assert.That(result.IsValid, Is.False);
		Assert.That(InvalidLocations(result), Has.Some.EqualTo("/PropertyVisibility/Sites/corporate/ContentTypes/landingPage/Propertes"));
	}

	[Test]
	public void AppSettingsSchema_rejects_a_misspelled_option()
	{
		var appSettings = ReplaceFirst(TestSiteAppSettings, "\"HideEmptiedContainers\"", "\"HideEmptiedContainer\"");

		var result = Evaluate(AppSettingsSchemaFile, appSettings);

		Assert.That(result.IsValid, Is.False);
		Assert.That(InvalidLocations(result), Has.Some.EqualTo("/PropertyVisibility/HideEmptiedContainer"));
	}

	[Test]
	public void ConfigFileSchema_accepts_the_sample_rules_file()
	{
		var result = Evaluate(ConfigFileSchemaFile, ConfigFileSample);

		Assert.That(result.IsValid, Is.True, Describe(result));
	}

	[Test]
	public void ConfigFileSchema_accepts_the_test_site_sample_rules_file()
	{
		var result = Evaluate(ConfigFileSchemaFile, TestSiteRulesFileSample);

		Assert.That(result.IsValid, Is.True, Describe(result));
	}

	[Test]
	public void The_test_site_sample_rules_file_loads_without_issues()
	{
		ConfigFileParseResult parsed = ConfigFileParser.Parse(Encoding.UTF8.GetBytes(TestSiteRulesFileSample), TestSiteRulesFileSampleName);

		Assert.Multiple(() =>
		{
			Assert.That(parsed.Issues, Is.Empty);
			Assert.That(parsed.Rules, Is.Not.Null);
		});
	}

	[Test]
	public void ConfigFileSchema_rejects_a_misspelled_key()
	{
		var rules = ReplaceFirst(ConfigFileSample, "\"Properties\"", "\"Propertes\"");

		var result = Evaluate(ConfigFileSchemaFile, rules);

		Assert.That(result.IsValid, Is.False);
		Assert.That(InvalidLocations(result), Has.Some.EqualTo("/Sites/corporate/ContentTypes/landingPage/Propertes"));
	}

	[Test]
	public void ConfigFileSchema_accepts_rule_sets_and_rejects_a_misspelled_key_in_one()
	{
		const string rules = """
			{
				"RuleSets": { "simplePages": { "ContentTypes": { "landingPage": { "Containers": ["seoTab"] } } } },
				"Sites": { "corporate": { "RootNodeKey": "5c2b4d7e-9f1a-4c3e-8b6d-2a1f0e9d8c7b", "Include": ["simplePages"] } }
			}
			""";

		SchemaResult valid = Evaluate(ConfigFileSchemaFile, rules);
		SchemaResult misspelled = Evaluate(ConfigFileSchemaFile, ReplaceFirst(rules, "\"ContentTypes\"", "\"ContentType\""));

		Assert.Multiple(() =>
		{
			Assert.That(valid.IsValid, Is.True, Describe(valid));
			Assert.That(misspelled.IsValid, Is.False);
			Assert.That(InvalidLocations(misspelled), Has.Some.EqualTo("/RuleSets/simplePages/ContentType"));
		});
	}

	[TestCase("Enabled", "false")]
	[TestCase("ConfigFile", "\"other.json\"")]
	public void ConfigFileSchema_rejects_appsettings_only_options(string key, string value)
	{
		var rules = ReplaceFirst(ConfigFileSample, "\"HideEmptiedContainers\"", $"\"{key}\": {value}, \"HideEmptiedContainers\"");

		var result = Evaluate(ConfigFileSchemaFile, rules);

		Assert.That(result.IsValid, Is.False);
		Assert.That(InvalidLocations(result), Has.Some.EqualTo("/" + key));
	}

	[Test]
	public void ConfigFileSchema_accepts_the_rules_of_the_appsettings_section_unchanged()
	{
		// The file holds the same shape and names as the section, minus the appsettings-only options.
		var section = JsonNode.Parse(TestSiteAppSettings, documentOptions: JsonWithComments)!["PropertyVisibility"]!.AsObject();
		section.Remove("Enabled");
		section.Remove("ConfigFile");

		var result = Evaluate(ConfigFileSchemaFile, section.ToJsonString());

		Assert.That(result.IsValid, Is.True, Describe(result));
	}

	/// <summary>
	///     Evaluates a JSON document against one of the committed schemas. They declare draft-04, like Umbraco's own
	///     appsettings schemas, and NJsonSchema evaluates them as such.
	/// </summary>
	private static SchemaResult Evaluate(string schemaFile, string json)
	{
		var schemaText = File.ReadAllText(PackageProjectFile(schemaFile));
		Assert.That(JsonNode.Parse(schemaText)!["$schema"]!.GetValue<string>(), Is.EqualTo("http://json-schema.org/draft-04/schema#"));

		return new SchemaResult(JsonSchemaValidation.Validate(schemaText, json));
	}

	/// <summary>Instance locations (JSON pointers) of every failure, the nested ones included.</summary>
	private static List<string> InvalidLocations(SchemaResult result) => result.Errors.Select(error => error.Location).ToList();

	private static string Describe(SchemaResult result) => JsonSchemaValidation.Describe(result.Errors);

	private static string ReplaceFirst(string text, string oldValue, string newValue)
	{
		var index = text.IndexOf(oldValue, StringComparison.Ordinal);
		Assert.That(index, Is.GreaterThanOrEqualTo(0), $"'{oldValue}' not found in the sample");
		return string.Concat(text.AsSpan(0, index), newValue, text.AsSpan(index + oldValue.Length));
	}

	private static string FindRepositoryRoot()
	{
		for (var directory = new DirectoryInfo(TestContext.CurrentContext.TestDirectory); directory is not null; directory = directory.Parent)
		{
			if (File.Exists(Path.Combine(directory.FullName, "Umbraco.Community.PropertyVisibility.slnx")))
			{
				return directory.FullName;
			}
		}

		throw new InvalidOperationException("Repository root (Umbraco.Community.PropertyVisibility.slnx) not found above the test output folder.");
	}

	private sealed record SchemaResult(IReadOnlyList<SchemaError> Errors)
	{
		public bool IsValid => Errors.Count == 0;
	}
}
