// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetUmbracoPropertyVisibilityV1HiddenFieldsData, GetUmbracoPropertyVisibilityV1HiddenFieldsErrors, GetUmbracoPropertyVisibilityV1HiddenFieldsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class PropertyVisibilityService {
    public static getUmbracoPropertyVisibilityV1HiddenFields<ThrowOnError extends boolean = false>(options?: Options<GetUmbracoPropertyVisibilityV1HiddenFieldsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoPropertyVisibilityV1HiddenFieldsResponses, GetUmbracoPropertyVisibilityV1HiddenFieldsErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/property-visibility/v1/HiddenFields',
            ...options
        });
    }
}
